apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hj27m67dk-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hj27m67dk-java-quarkus-gitops